# Form implementation generated from reading ui file 'check_in.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import *

class CheckIn(QWidget):

    def __init__(self, ticket_name, sponsorship_level):
        super().__init__()
        self._ticket_name = ticket_name
        self._sponsorship_level = sponsorship_level
        self._checked_in = False
        self._layout = QHBoxLayout()
        self._name_display = QLabel(self._ticket_name)
        self._sponsorship_display = QLabel(self._sponsorship_level)
        self._button = QPushButton("Not Yet Checked In")
        self._layout.addWidget(self._name_display)
        self._layout.addWidget(self._sponsorship_display)
        self._layout.addWidget(self._button)
        self.setLayout(self._layout)
